### PR TITLE
Update storage_list.xml

### PR DESCRIPTION
**Pull request by CertainLach**
Internal Sdcard

### CODE REVIEW

**Comment by high1** [comment]
This could work, maybe. Have you tested it? I will not pull in anything untested at this point.
I think you need to add a fuse service entry for internal sdcard too in init.golfu.rc...
Also, internal sdcard is vfat, isn't it? And mount point could be /emmc... But, is there any point in this - I see 95MB in TRWP, where we mount internal storage - but maybe I have something there? Review this ASAP...

**Comment by CertainLach** [comment]
I have testted that. Internal sdcard mounts at /mnt/emmc on stock rom. Internal sdcard is vfat, but i can't edit this commit (That is strange). I have dont tested storage_list.xml, but it should work. And symlink to /storage/sdcard1 is not required, but I think that one /storage/sdcard0 boring :smile:

**Comment by high1** [comment]
Is there any point in this? How much storage is there, anyway? My /emmc is 95Mb, and that is so minor that I do not see the need for this. How large is it on your phone? If you mount it like this, it is a static mount, and not a vold managed one. Look at how I mount external sdcard. Also, I have not seen anyone mount emmc partition in previous Cyanogenmod iterations.

**Comment by CertainLach** [comment]
In any version of CyanogenMod nobody edited it, because this partition is too small. But mount it is not a problem, and this is usable for swap.

**Comment by CertainLach** [comment]
On all phones this partition 95mb

**Comment by high1** [comment]
Then I really do not see the point in anything else but swap... But we already have swap to zRAM so if you figure out how to mount it as swap, I will review the patch then.

**Comment by CertainLach** [comment]
For swap i use "Swapper for ROOT", but i try to make a way to mount this automatically

**Comment by high1** [comment]
Will not merge anything that requires third party software. Closing this as it is just not worth it to use as storage. Makes me think that it is useless in TWRP too.

**Comment by CertainLach** [comment]
Swap can be enabled by adding
    #SWAP
    dd if=/dev/zero of=/mnt/emmc/.swap bs=1024 count=80m
    mkswap /mnt/emmc/.swap
    sync
    swapon /mnt/emmc/.swap
in init.golfu.rc

**Comment by CertainLach** [comment]
Swap added in commit

**Comment by CertainLach** [comment]
https://github.com/Creeplays/android_device_htc_golfu/blob/patch-1/ramdisk/init.golfu.rc, line 127

**Pull request closed without merging**
